name: Goose Do It

on:
  issues:
    types:
      - labeled
  issue_comment:
    types:
      - created      

jobs:
  ask-goose:
    if: github.event.label.name == 'goose' or ${{ github.event.issue.pull_request && contains(github.event.comment.body, '@goose-ai') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pipx
        run: python -m pip install --user pipx

      - name: Install Goose AI
        run: |
          pipx install goose-ai
          pipx inject goose-ai keyrings.alt

      - name: Run Goose Action
        uses: michaelneale/goose-fix-it-action@main
        with:
          task_request: |
            ${{ github.event.issue.title }}
            ${{ github.event.issue.body }}
            [Link to issue](${{ github.event.issue.html_url }})
          validation: "check the vite web app installs"  
          create_pr: 'true'
          update_pr: 'true'        
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Change this in your repo secrets
          GH_TOKEN: ${{ github.token }}